services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "51214:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
